action_id: trunk-single-player-auto-upgrade
date: 2025-08-21 22:58:27
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1755817107
full_timestamp:
  nanos: 530042000
  seconds: 1755817107
trunk_version: 1.25.0
