@echo off
REM Generated by trunk tool 'hadolint'
set PATH=C:\Users\SURFACE\AppData\Local\trunk\tools\hadolint\2.12.1-beta-687495f5930658f12fa336f5ce061c74;C:\Users\SURFACE\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\SURFACE\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b hadolint %*
