@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\SURFACE\AppData\Local\trunk\tools\osv-scanner\2.2.1-9fc43d91e8dfd0e44c4cbd42616f333f;C:\Users\SURFACE\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\SURFACE\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
